def generate_pipeline_code(pipeline_steps):
    """
    Generates a Python script for the sklearn pipeline based on the recorded steps.
    pipeline_steps: list of dictionaries
    """
    code = []
    code.append("import pandas as pd")
    code.append("import numpy as np")
    code.append("from sklearn.pipeline import Pipeline")
    code.append("from sklearn.base import BaseEstimator, TransformerMixin")
    code.append("from sklearn.impute import SimpleImputer")
    code.append("from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, OneHotEncoder, LabelEncoder")
    code.append("")
    code.append("# Custom Transformers")
    code.append("class ColumnDropper(BaseEstimator, TransformerMixin):")
    code.append("    def __init__(self, columns):")
    code.append("        self.columns = columns")
    code.append("    def fit(self, X, y=None):")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        return X.drop(columns=self.columns, errors='ignore')")
    code.append("")
    code.append("class RowDropper(BaseEstimator, TransformerMixin):")
    code.append("    def __init__(self, subset):")
    code.append("        self.subset = subset")
    code.append("    def fit(self, X, y=None):")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        return X.dropna(subset=self.subset)")
    code.append("")
    code.append("class DuplicateRemover(BaseEstimator, TransformerMixin):")
    code.append("    def fit(self, X, y=None):")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        return X.drop_duplicates()")
    code.append("")
    code.append("class SingleColumnImputer(BaseEstimator, TransformerMixin):")
    code.append("    def __init__(self, column, strategy):")
    code.append("        self.column = column")
    code.append("        self.strategy = strategy")
    code.append("        self.fill_value = None")
    code.append("    def fit(self, X, y=None):")
    code.append("        if self.strategy == 'mean':")
    code.append("            self.fill_value = X[self.column].mean()")
    code.append("        elif self.strategy == 'median':")
    code.append("            self.fill_value = X[self.column].median()")
    code.append("        elif self.strategy == 'mode':")
    code.append("            self.fill_value = X[self.column].mode()[0]")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        X = X.copy()")
    code.append("        if self.fill_value is not None:")
    code.append("            X[self.column] = X[self.column].fillna(self.fill_value)")
    code.append("        return X")
    code.append("")
    code.append("class CustomLabelEncoder(BaseEstimator, TransformerMixin):")
    code.append("    def __init__(self, columns):")
    code.append("        self.columns = columns")
    code.append("        self.encoders = {}")
    code.append("    def fit(self, X, y=None):")
    code.append("        for col in self.columns:")
    code.append("            le = LabelEncoder()")
    code.append("            le.fit(X[col].astype(str))")
    code.append("            self.encoders[col] = le")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        X = X.copy()")
    code.append("        for col in self.columns:")
    code.append("            if col in self.encoders:")
    code.append("                X[col] = self.encoders[col].transform(X[col].astype(str))")
    code.append("        return X")
    code.append("")
    code.append("class CustomOneHotEncoder(BaseEstimator, TransformerMixin):")
    code.append("    def __init__(self, columns):")
    code.append("        self.columns = columns")
    code.append("        self.encoder = None")
    code.append("    def fit(self, X, y=None):")
    code.append("        self.encoder = OneHotEncoder(sparse_output=False, drop=None, handle_unknown='ignore')")
    code.append("        self.encoder.fit(X[self.columns])")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        X = X.copy()")
    code.append("        encoded_data = self.encoder.transform(X[self.columns])")
    code.append("        feature_names = self.encoder.get_feature_names_out(self.columns)")
    code.append("        encoded_df = pd.DataFrame(encoded_data, columns=feature_names, index=X.index)")
    code.append("        X = X.drop(columns=self.columns)")
    code.append("        X = pd.concat([X, encoded_df], axis=1)")
    code.append("        for col in encoded_df.columns:")
    code.append("             X[col] = X[col].astype(int)")
    code.append("        return X")
    code.append("")
    code.append("class CustomScaler(BaseEstimator, TransformerMixin):")
    code.append("    def __init__(self, columns, method):")
    code.append("        self.columns = columns")
    code.append("        self.method = method")
    code.append("        self.scaler = None")
    code.append("    def fit(self, X, y=None):")
    code.append("        if self.method == 'StandardScaler (Z-score)':")
    code.append("            self.scaler = StandardScaler()")
    code.append("        elif self.method == 'MinMaxScaler (0-1)':")
    code.append("            self.scaler = MinMaxScaler()")
    code.append("        elif self.method == 'RobustScaler (less affected by outliers)':")
    code.append("            self.scaler = RobustScaler()")
    code.append("        if self.scaler:")
    code.append("            self.scaler.fit(X[self.columns])")
    code.append("        return self")
    code.append("    def transform(self, X):")
    code.append("        X = X.copy()")
    code.append("        if self.scaler:")
    code.append("            X[self.columns] = self.scaler.transform(X[self.columns])")
    code.append("        return X")
    code.append("")
    
    code.append("def create_pipeline():")
    code.append("    steps = []")
    
    for i, step in enumerate(pipeline_steps):
        step_name = f"step_{i}_{step['type']}"
        
        if step['type'] == 'drop_columns':
            code.append(f"    steps.append(('{step_name}', ColumnDropper(columns={step['columns']})))")
        
        elif step['type'] == 'drop_rows':
            code.append(f"    steps.append(('{step_name}', RowDropper(subset={step['columns']})))")
            
        elif step['type'] == 'impute':
            code.append(f"    steps.append(('{step_name}', SingleColumnImputer(column='{step['column']}', strategy='{step['strategy']}')))")
                
        elif step['type'] == 'remove_duplicates':
            code.append(f"    steps.append(('{step_name}', DuplicateRemover()))")
            
        elif step['type'] == 'label_encoding':
            code.append(f"    steps.append(('{step_name}', CustomLabelEncoder(columns={step['columns']})))")
            
        elif step['type'] == 'one_hot_encoding':
            code.append(f"    steps.append(('{step_name}', CustomOneHotEncoder(columns={step['columns']})))")

        elif step['type'] == 'scale':
            code.append(f"    steps.append(('{step_name}', CustomScaler(columns={step['columns']}, method='{step['method']}')))")
            
    code.append("")
    code.append("    return Pipeline(steps)")
    code.append("")
    code.append("if __name__ == '__main__':")
    code.append("    # Example usage:")
    code.append("    # df = pd.read_csv('your_data.csv')")
    code.append("    # pipeline = create_pipeline()")
    code.append("    # df_cleaned = pipeline.fit_transform(df)")
    code.append("    pass")
    
    return "\n".join(code)
